### ISSUE TITLE
Refactor large components 

### ISSUE THREAD

**Issue by sjha2048** [fossology/FOSSologyUI#108]
### Description

There are several components which needs to be refactored/broken into smaller components

**Comment by DawnArchi01** [comment]
Hey , I would like to know more on the issue .

**Comment by Raunakk02** [comment]
Hi @sjha2048 @Shruti3004, If no one's working on this issue then can I take this up? There are many open issues on this repo and many people have already commented for taking up the issues. But as of now, those requests are pretty old and still, no one has been assigned to the issue. So please let me know if the project is still accepting contributors.

**Comment by Raunakk02** [comment]
Thanks for the response @mcjaeger. Really appreciate it!
I will start working on this issue now.

**Comment by sjha2048** [comment]
Hi @Raunakk02, sorry somehow I missed your reply.

feel free to take up this issue and reach out to me in case of any issues/discussions, for now, I'll assign this to you.

**Comment by mcjaeger** [comment]
Hi, in case you would have the time, maybe consider outlining what your plans are? So we could give feedback and adjust in case. By that approach you re avoiding to work on a PR for a long time alone and then publish something which overlooked one thing in the beginning.

**Comment by Raunakk02** [comment]
Sure @mcjaeger, I'll let you know about my plans once I am done outlining them.

**Comment by Raunakk02** [comment]
@mcjaeger @sjha2048 Here is the outline of the work that I am planning to do for the first PR targeting this issue.

## Potential Refactoring

-   src/components/

    -   BrowseUploadsHeader:

        -   The `<Link></Link>` componenent can be taken out as a separate component.

    -   Header:

        -   The `<Nav.Link></Nav.Link>` componenent can be taken out as a separate component -> (not much impact on the file size)
        -   The `<NavDropdown></NavDropdown>` componenents can be taken out as a separate component -> (Major impact on file size).
            Routes and Names for `<NavDropdown.Item></NavDropdown.Item>` can be loaded from a map present in an external .js file thereby further reducing the file size.
        -   The nested `<DropdownButton></DropdownButton>` in some `NavDropdown.Item` can also be extracted as a separate component.

    -   Table:

        -   The `<div className="paginationTable">` can be extracted out as a separate component.

    -   Upload\CommonFields:

        -   The `AccessLevel, LicenseDecider, OptionalAnalysis, UploadReuse` components contains similar instances of `<InputContainer>` which can be efficiently refactored using a string processing utility to generate the name, id, and checked attributes for the `<InputContainer>` component.

-   src/pages/

    This folder also contains many components that can be refactored like `Admin/Users/Delete`, `Browse`, `Jobs/ScheduleAgents` but in the first PR, I'll be just focusing on the refactoring the files present in the `src/components` folder.

**Comment by sjha2048** [comment]
Hi @Raunakk02 Thank you for the pull request, I'll drop my review soon.
