### ISSUE TITLE
Browse folder uploads

### ISSUE THREAD

**Issue by GMishx** [fossology/FOSSologyUI#131]
### Description

Since Browse page now list uploads and folders, the uploads navigation can be updated. When someone clicks on a folder, the uploads from that folder can be listed in the browse table.

This task can be picked-up when migrating to material table as well.

**Comment by Shruti3004** [comment]
Yeah Actually we are not sure about that we are going to use both libraries in the project, and even we had a discussion with sahil on this in the last meeting but we doesn't reached to any conclusion probably we can discuss it today's meeting.
