### ISSUE TITLE
Move texts/messages to a constant file

### ISSUE THREAD

**Issue by sjha2048** [fossology/FOSSologyUI#156]
At several places, we have hardcoded error messages, these can be moved to a separate constants file.

**Comment by caffeinated-pixels** [comment]
Hi. I've just had a quick look and I believe this is something I could take on if you want to assign me?

Just to clarify: you want me to find all the hardcoded error messages, move them to a single constants file, and then import the messages as variables where needed? 

Thanks
Stevie

**Comment by sjha2048** [comment]
Hey @caffeinated-pixels, 
yes, you are correct, we want to do it for all kinds of messages.
