### ISSUE TITLE
Use lazy loading components

### ISSUE THREAD

**Issue by Aman-Codes** [fossology/FOSSologyUI#160]
### Description

Currently all the components are loaded during initial page load which increases the initial load time. We could use [lazy loading](https://blog.logrocket.com/lazy-loading-components-in-react-16-6-6cea535c0b52/) to optimize the load time. 

#### Steps followed and expected result

Update imports to use lazy loading. Example change
```jsx
import Home from "./Home";
```
to
```jsx
const Home = React.lazy(() => import("./Home"));
```

**Comment by viogustian** [comment]
do i just have to lazy loaded all in the components folder?

**Comment by Aman-Codes** [comment]
@viogustian I believe just updating all the page imports inside the [Routes file](https://github.com/fossology/FOSSologyUI/blob/main/src/Routes.jsx) would work.

**Comment by sayantan1413** [comment]
@Aman-Codes Is this issue still open then I would like to contribute here.

**Comment by TC5022** [comment]
I would like to work on this issue if it's still open

**Comment by soham4abc** [comment]
I Have started working on this pls assign me the issue if possible.
