### ISSUE TITLE
Create storybook item for all the components

### ISSUE THREAD

**Issue by Aman-Codes** [fossology/FOSSologyUI#161]
### Description

Create [storybook item](https://storybook.js.org/docs/react/writing-stories/introduction) for all the components.

#### Steps followed and expected result

Sample [storybook](https://next--storybookjs.netlify.app/official-storybook/)

#### Screenshots

![image](https://user-images.githubusercontent.com/54680709/136145598-5ae8ce0b-7d07-420c-9a5a-3e1637b0a9fa.png)

**Comment by Jacoberson** [comment]
Can I work on this?

**Comment by Shruti3004** [comment]
Go ahead @Jacoberson

**Comment by soham4abc** [comment]
@Aman-Codes  Is this issue still open. I would like to work on this issue!

**Comment by TC5022** [comment]
I would like to work on this issue

**Comment by shlokjjw** [comment]
Is any collaborative work possible on this issue?

**Comment by RakeshPotnuru** [comment]
Hi @Aman-Codes 
I know storybook, can I work on this?

**Comment by Shruti3004** [comment]
Yes sure @RakeshPotnuru
