### ISSUE TITLE
Update version information

### ISSUE THREAD

**Issue by GMishx** [fossology/FOSSologyUI#168]
There is a new PR in fossology upstream to expose server information via REST API https://github.com/fossology/fossology/pull/2139

The following code needs to be tested and updated if required. The API also expose other information like version, branch name and commit hash which should also be displayed on the UI.

https://github.com/fossology/FOSSologyUI/blob/850d3c5153bc4fd02f4d87403da965debe5fee22/src/services/info.js#L31-L32

**Comment by soham4abc** [comment]
I can work on this issue. Will you please assign me?

**Comment by Ananyaas** [comment]
Hi, Can I work on this issue?

**Comment by Shruti3004** [comment]
Hey @soham4abc are you still want to work on this issue?

**Comment by soham4abc** [comment]
> Hey @soham4abc are you still want to work on this issue?

No ... let @Ananyaas have this issue... :-)

**Comment by Shruti3004** [comment]
Cool @Ananyaas you can work on this issue.

**Comment by pret3nti0u5** [comment]
Hey, is this issue still being worked on? 
I can take it up if not.

**Comment by sjha2048** [comment]
@Ananyaas are you stuck anywhere or would you like to have a discussion?

**Comment by Ankur0710** [comment]
hii this is ankur nigam i want to work on this issue can you please assign this to me

**Comment by sjha2048** [comment]
Sure @Ankur0710 I'll assign it to you.

**Comment by omkarg01** [comment]
If this issue is still open, I would like to work on it. @sjha2048 Would u please assign it to me?

**Comment by krishna9304** [comment]
Hi, Can I take up this issue if it's not being worked on?

**Comment by sjha2048** [comment]
apologies for the delayed response, @Ankur0710 are you still working on it?

**Comment by nisKULDEEP** [comment]
Hello everyone, can someone help me to assign this task to me?

**Comment by GMishx** [comment]
At the moment, I am not sure assigning issue makes any sense. Please create a PR if you are working on it.

**Comment by Ankur0710** [comment]
Sir I am on ,  sir I had some problem at home so I could not do it, so now I will do this issue guide me please reply as soon as possible

**Comment by Ankur0710** [comment]
please tell me how i start

**Comment by Ankur0710** [comment]
please resign me

**Comment by soham4abc** [comment]
![image](https://user-images.githubusercontent.com/63705023/161545690-42be418d-c2b6-4a4c-b9d6-ca81ab92cb64.png)

This is the current state of the UI end.. What update does it need kindly anyone can inform ? @GMishx  
Plus the API returns the version as `unknown`.

![image](https://user-images.githubusercontent.com/63705023/161546092-5aa2294d-5389-4086-a690-343c316e12d7.png)

(I am running the latest fossology backend from main using docker)

I proposed a bit different layout like this:

![image](https://user-images.githubusercontent.com/63705023/161408753-593f3c4e-0c5a-4153-8566-7ab32deeb02b.png)

**Comment by pret3nti0u5** [comment]
Actually @soham4abc, even the Version is displayed correctly in the current UI. As can be seen here.
![image](https://user-images.githubusercontent.com/57453561/161558536-870d0758-d8c6-48f3-80a4-0837e04c596a.png)

Unless @GMishx has any changes to the current state I think it is safe to close this issue.

**Comment by soham4abc** [comment]
> Actually @soham4abc, even the Version is displayed correctly in the current UI. As can be seen here. ![image](https://user-images.githubusercontent.com/57453561/161558536-870d0758-d8c6-48f3-80a4-0837e04c596a.png)
> 
> Unless @GMishx has any changes to the current state I think it is safe to close this issue.

I too think the same. The thing is already being implemented in the current state of the UI. Unless any change is required in  the layout.  Thanks for your input @pret3nti0u5

**Comment by GMishx** [comment]
Indeed you guys are correct. I think I didn't notice the naming used in REST API matches the naming in repo. This issue can be closed.

**Comment by GMishx** [comment]
> ![image](https://user-images.githubusercontent.com/63705023/161545690-42be418d-c2b6-4a4c-b9d6-ca81ab92cb64.png)
> 
> This is the current state of the UI end.. What update does it need kindly anyone can inform ? @GMishx Plus the API returns the version as `unknown`.
> 
> ![image](https://user-images.githubusercontent.com/63705023/161546092-5aa2294d-5389-4086-a690-343c316e12d7.png)
> 
> (I am running the latest fossology backend from main using docker)
> 
> I proposed a bit different layout like this:
> 
> ![image](https://user-images.githubusercontent.com/63705023/161408753-593f3c4e-0c5a-4153-8566-7ab32deeb02b.png)

@soham4abc for the `unknown` version, can you please create an issue in FOSSology? I think the docker image does not have `.git` folder which causes it to be missing.

**Comment by soham4abc** [comment]
> > ![image](https://user-images.githubusercontent.com/63705023/161545690-42be418d-c2b6-4a4c-b9d6-ca81ab92cb64.png)
> > 
> > This is the current state of the UI end.. What update does it need kindly anyone can inform ? @GMishx Plus the API returns the version as `unknown`.
> > 
> > ![image](https://user-images.githubusercontent.com/63705023/161546092-5aa2294d-5389-4086-a690-343c316e12d7.png)
> > 
> > (I am running the latest fossology backend from main using docker)
> > 
> > I proposed a bit different layout like this:
> > 
> > ![image](https://user-images.githubusercontent.com/63705023/161408753-593f3c4e-0c5a-4153-8566-7ab32deeb02b.png)
> 
> @soham4abc for the `unknown` version, can you please create an issue in FOSSology? I think the docker image does not have `.git` folder which causes it to be missing.

Sure I will be creating the Issue ASAP!

**Comment by soham4abc** [comment]
Created : https://github.com/fossology/fossology/issues/2206

@GMishx
