### ISSUE TITLE
Setup on local

### ISSUE THREAD

**Issue by Suman-Jaiswal** [fossology/FOSSologyUI#172]
Could somebody please help me to make setup on local?
I have run the docker commands mentioned in the 'README' file, after that if I put user: 'fossy', and password: 'fossy' I am getting failed to fetch error.

![Screenshot (162)](https://user-images.githubusercontent.com/80769590/151666109-f564854c-4dff-4e63-8bde-b9207993ca93.png)

**Comment by Shruti3004** [comment]
Hey @Suman-Jaiswal have you setup this https://github.com/fossology/fossology repository. In addition to that can you check your network tab and add the screenshot here.

**Comment by Suman-Jaiswal** [comment]
![Screenshot 2022-01-29 205950](https://user-images.githubusercontent.com/80769590/151666815-abcd876e-6319-4219-ac69-94c049ea7bed.png)

**Comment by Suman-Jaiswal** [comment]
I think the network setup is not there. I am new to docker. could you please help me out?. I will also update the readme file if required.

**Comment by Suman-Jaiswal** [comment]
![Screenshot (163)](https://user-images.githubusercontent.com/80769590/151672044-2c815664-f76c-4711-9cfd-dd55161a4145.png)

**Comment by Suman-Jaiswal** [comment]
ma'am, I set that repo on my local and successfully logged in. Thanks

**Comment by Shruti3004** [comment]
Great, let me know in case of any further queries. I am closing this issue.
