### ISSUE TITLE
Dark theme toggle button 

### ISSUE THREAD

**Issue by mayank2021** [fossology/FOSSologyUI#173]
### Description
When someone click on the profile then only he/she can able to know about the dark theme. To create better user experience the dark theme button should be on navigation.

#### Steps followed and expected result
Current situation:-
1.For toggling between dark theme and light theme we have two button elements
2.User will able to know about the dark theme only when he/she click on the profile
![image](https://user-images.githubusercontent.com/55187056/154129184-f2962202-f042-4b6b-877c-3be058336aee.png)

Expected situation:-
1. make a single button element to improve the user experience 
2.Put the toggle button on top to visible clearly.
![image](https://user-images.githubusercontent.com/55187056/154129256-bcc1c3ff-b1a9-452b-83f4-cfef491cc442.png)

**Comment by Shruti3004** [comment]
Hey @mayank2021 do you want to take this issue up?

**Comment by mayank2021** [comment]
@Shruti3004 I am glad to work on that!

**Comment by Shruti3004** [comment]
Go ahead @mayank2021

**Comment by mayank2021** [comment]
@Shruti3004 Thanks!

**Comment by mayank2021** [comment]
@Shruti3004 I need to maintain a state after refresh, so what do you think the best place would be, local storage or something else?

**Comment by GMishx** [comment]
Just one thing I would like to mention, the button should not consume much of the UI space. The feature is not used very frequently by users. At most twice a day maybe?

The current theme change is hidden under a drop down so it is not consuming any space.

**Comment by mayank2021** [comment]
@GMishx Thank you for the suggestion, I will keep it in my mind!
