### ISSUE TITLE
Login button alignment issue

### ISSUE THREAD

**Issue by mayank2021** [fossology/FOSSologyUI#175]
### Description
login button is not perfectly aligned with input elements

### Current situation 
![image](https://user-images.githubusercontent.com/55187056/154456376-09bebc86-bf1d-4009-bdf5-07c231b80cf7.png)

### Expected result
![image](https://user-images.githubusercontent.com/55187056/154456488-e9991514-615c-4d86-8115-cc9607f616b7.png)

**Comment by mayank2021** [comment]
@Shruti3004 @GMishx Can I take this up?

**Comment by GMishx** [comment]
Sure

**Comment by soham4abc** [comment]
@GMishx  I already had this fixed :'-)

**Comment by soham4abc** [comment]
> If the change is limited to the layout then please create the PR @soham4abc

on it

**Comment by mayank2021** [comment]
@GMishx @soham4abc don't you think the mobile UI should have the equal spaces between all the element

like the image given below
![image](https://user-images.githubusercontent.com/55187056/154504131-183f3dc9-ca09-45ea-9006-c956bb142a18.png)

I am done with the code if @soham4abc can fix the issue than it's good otherwise let me know just need to create a pr
