### ISSUE TITLE
Issue templates now use Issue forms instead of markdown

### ISSUE THREAD

**Issue by Ayush7614** [fossology/FOSSologyUI#184]
Markdown templates often made it difficult to capture the whole context, by expecting the contributors to read the markup, uncomment lines and delete relevant context.

Issue forms beta was released for public repositories last month, as mentioned by GitHub on this [blog](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). We would like to migrate the issue templates to YAML-based forms which are easy to fill up and maintain, helping us capture relevant context.

There is no issue templates in the project so i would like to work on the issue

**Comment by Ayush7614** [comment]
@maxhbr @Shruti3004

**Comment by sjha2048** [comment]
I will research more on this, for now, can you move this to https://github.com/fossology/FOSSologyUI/discussions ?

**Comment by GMishx** [comment]
I agree with @sjha2048 . And in my opinion, it will be premature to move to issue forms at the moment.

**Comment by GMishx** [comment]
Moved to https://github.com/fossology/FOSSologyUI/discussions/189

Closing the issue.
