### ISSUE TITLE
Creation of `all recent jobs` page

### ISSUE THREAD

**Issue by soham4abc** [fossology/FOSSologyUI#222]
### Description

Currently, the `/allRecentJobs` page is not implemented as it gives us a blank response. 

#### Steps followed and expected result
Run the UI with the current backend and after login visit the All recent jobs page

PS: I would like to work on this issue

@shaheemazmalmmd @GMishx

**Comment by shaheemazmalmmd** [comment]
@soham4abc you can start working on it.
