### ISSUE TITLE
Need script to generate copyright information

### ISSUE THREAD

**Issue by GMishx** [fossology/FOSSologyUI#27]
I have a request to generate the `src/data/copyright.js` file (from PR #23) from CSV exported from FOSSology. It will make it very easy to update the list from FOSSology scan results.

Also, please do a unique operation on the final list to remove duplicates.

Attaching sample file for reference.

[atarashi-master.zip-20210624-copyrights.csv](https://github.com/fossology/FOSSologyUI/files/6706334/atarashi-master.zip-20210624-copyrights.csv)

**Comment by Shruti3004** [comment]
@GMishx if possible can I get the csv for copyrights.

**Comment by GMishx** [comment]
I have already attached one sample in the description. Do you want the CSV for FOSSology?

**Comment by Shruti3004** [comment]
> I have already attached one sample in the description. Do you want the CSV for FOSSology?

Yes, if possible then it will be great so that I can dry run the things, because instead of array I thought to do it with the JSON, and the JSON format for the following is: 
```
[
     {
           "filepath" : "atarashi..",
           "copyright" : ".........",       
     }
]
```
But I want to look how the json of these copyrights will look like because I think we don't need keys for the copyrights in the json

**Comment by GMishx** [comment]
So I couldn't find the file which generated the copyrights in the About page. But I just cleared the copyrights for FOSSology again and here is the CSV: [fossology-01-07-2021-20210701-copyrights.csv](https://github.com/fossology/FOSSologyUI/files/6748092/fossology-01-07-2021-20210701-copyrights.csv)

From the last comment, I also don't think you need to mention any `filepath` of the `copyright` keyword. Just reading the `copyright` column from CSV, getting the unique values and dumping the list will be enough.
