### ISSUE TITLE
General review on current stage

### ISSUE THREAD

**Issue by GMishx** [fossology/FOSSologyUI#63]
### Description

Some observations on current `development` branch.
1. Tried dark theme on Search page, results not looking good.
2. The page "Organize > Folder > Move or Copy" has title "Move folder" where copy is also a posibility.
3. Please check the link for "FOSSology web site" in the bottom of "http://localhost:3000/help/overview" to open in new tab.

#### Screenshots

- Search
    ![image](https://user-images.githubusercontent.com/18077542/124344339-1de2c680-dbef-11eb-89df-6cec515d6745.png)
- Copy Folder
    ![image](https://user-images.githubusercontent.com/18077542/124344415-a8c3c100-dbef-11eb-86da-4d46e19d7e98.png)

### Versions

* Last commit id on development: c6fe109a0be32a21e867acb3ace86b21f2871906
* Browser [e.g. chrome, safari]: Firefox 89.0.2

**Comment by Shruti3004** [comment]
> ### Description
> Some observations on current `development` branch.
> 
> 1. Tried dark theme on Search page, results not looking good.
> 2. The page "Organize > Folder > Move or Copy" has title "Move folder" where copy is also a posibility.
> 3. Please check the link for "FOSSology web site" in the bottom of "http://localhost:3000/help/overview" to open in new tab.
> 
> #### Screenshots
> * Search
>   ![image](https://user-images.githubusercontent.com/18077542/124344339-1de2c680-dbef-11eb-89df-6cec515d6745.png)
> * Copy Folder
>   ![image](https://user-images.githubusercontent.com/18077542/124344415-a8c3c100-dbef-11eb-86da-4d46e19d7e98.png)
> 
> ### Versions
> * Last commit id on development: [c6fe109](https://github.com/fossology/FOSSologyUI/commit/c6fe109a0be32a21e867acb3ace86b21f2871906)
> * Browser [e.g. chrome, safari]: Firefox 89.0.2

@GMishx I have already fixed this search theme issue in the pr #61

**Comment by Shruti3004** [comment]
@GMishx Created the separate pr fixing the listed issues. #65

**Comment by GMishx** [comment]
Fixed in #65 and #66
