### ISSUE TITLE
Snackbars for error/success  messages

### ISSUE THREAD

**Issue by sjha2048** [fossology/FOSSologyUI#67]
### Description

For error handling and showing successful responses to users, we can have snack bars 

#### Screenshots
Component for reference 

![image](https://user-images.githubusercontent.com/30971724/124355457-e7c53700-dc2e-11eb-8ba4-73119663826b.png)

#### References

https://material-ui.com/components/snackbars/

**Comment by Shruti3004** [comment]
#78 is merged.
