### ISSUE TITLE
Create a docker compose file with fossology backend

### ISSUE THREAD

**Issue by sameer1046** [fossology/FOSSologyUI#85]
Unable to use the UI with a Fossology backend due to cross origin policy.

Please create a docker compose file with Fossology backend for containerized execution.

**Comment by Shruti3004** [comment]
Hey, @sameer1046 have you tried changing the port Admin>Customize

**Comment by sameer1046** [comment]
Please make the apiUrl configurable in a config file
The app is not working in windows due to error " delete ‘␍’eslint (prettier / prettier) error"

**Comment by Aman-Codes** [comment]
@sameer1046 Yes there is already a pull request (#69) for keeping apiUrl in a separate .env file

**Comment by GMishx** [comment]
Hello @sameer1046 PR #69 will put the apiUrl in an `.env` file.
