### ISSUE TITLE
Use scan preference from user object

### ISSUE THREAD

**Issue by GMishx** [fossology/FOSSologyUI#88]
### Description

While uploading a file or scheduling a scan from Jobs, the list of agents can be selected by default based on `/users/self` object.

Currently, following object is returned from the `/users/self` endpoint
```json
{
  "id": 3,
  "name": "fossy",
  "description": "Default Administrator",
  "email": "me@local.domain",
  "accessLevel": "admin",
  "rootFolderId": 1,
  "emailNotification": "y",
  "agents": {
    "bucket": false,
    "copyright_email_author": true,
    "ecc": true,
    "keyword": true,
    "mimetype": true,
    "monk": true,
    "nomos": true,
    "ojo": true,
    "package": true
  }
}
```

The `agents` object here is what user has selected as their default agents in the UI. This can be used to select the checkboxes from the following table.

![image](https://user-images.githubusercontent.com/18077542/124745496-80b0c680-df3d-11eb-876d-9a74b176f51b.png)

**Comment by Aman-Codes** [comment]
Closed by #92
