### ISSUE TITLE
Load the reuse options

### ISSUE THREAD

**Issue by GMishx** [fossology/FOSSologyUI#89]
### Description

In the current UI, only "Enhanced reuse" and "Reuse main license" options exists.

#### Steps followed and expected result

1. The "Select an already uploaded package for reuse in specific folder" option is just a list of folder. Can be populated with `/folders` endpoint.
2. Other 2 options of report configuration and copyrights are `reuse_report` and `reuse_copyright` boolean.
3. "Upload to reuse" is another list of uploads within the selected folder, much like `organize/uploads/edit` page.
4. One additional input `reuse_group` will be required and can be populated from `/groups` endpoint.
    - Since the uploads inside a folder can be visible/hidden based on group, this option should be before the uploads list.
    - Whenever the selected group changes, the list of uploads needs to be refreshed.
    - The call to `/uploads?folderId=<id>` can be done with `groupName` header holding the selected value.

#### Screenshots

- Current UI
    - ![image](https://user-images.githubusercontent.com/18077542/124747752-e7cf7a80-df3f-11eb-8d86-e3b70093ca5b.png)
- UI from FOSSology
    - ![image](https://user-images.githubusercontent.com/18077542/124747666-cb334280-df3f-11eb-895a-248ad956d9bb.png)

**Comment by Shruti3004** [comment]
Okay @GMishx will work on it.
