### ISSUE TITLE
Spinner on browse page

### ISSUE THREAD

**Issue by GMishx** [fossology/FOSSologyUI#91]
### Description

A spinner can be displayed on the "Browse" page while waiting for response from API.

Should be visible for both initial load and when going to next page.

#### Steps followed and expected result

Kill apache server and then perform operation on the page.

#### Screenshots

Current spinner is not very visual and also does not handle errors.

![image](https://user-images.githubusercontent.com/18077542/124749764-4695f380-df42-11eb-9096-660553a14e80.png)

**Comment by Shruti3004** [comment]
> ### Description
> A spinner can be displayed on the "Browse" page while waiting for response from API.
> 
> Should be visible for both initial load and when going to next page.
> 
> #### Steps followed and expected result
> Kill apache server and then perform operation on the page.
> 
> #### Screenshots
> Current spinner is not very visual and also does not handle errors.
> 
> ![image](https://user-images.githubusercontent.com/18077542/124749764-4695f380-df42-11eb-9096-660553a14e80.png)

Okay will fix it.
