### ISSUE TITLE
License text hard to read in dark theme

### ISSUE THREAD

**Issue by GMishx** [fossology/FOSSologyUI#97]
### Description

The text in disabled textarea is hard to read in dark theme.

#### How to reproduce

Load licenses from Organize > Licenses and change the theme to dark.

#### Screenshots

![image](https://user-images.githubusercontent.com/18077542/125235018-6b51e880-e2ff-11eb-8ea7-e6393f0b24d0.png)

**Comment by Shruti3004** [comment]
@GMishx Fixed it in #83
